version: '3.8'
services:
  server:
    build: ./
    image: lms
    container_name: lms
    ports:
      - "8080:8080"
    depends_on:
      - db-lms
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-lms:5432/lms-db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  db-lms:
    image: postgres:14-alpine
    container_name: db-lms
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lms-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password