-- добавление тестовых данных
DELETE
FROM lessons
WHERE lessons.id_lesson > 0;

DELETE
FROM users
WHERE users.id_user > 0;
INSERT INTO users (name, surname, login, password, token, email, date_birth, date_registration, avatar_url)
VALUES ('Анна', 'Савельева', 'irinasav', 'treerinxlx864xn', 'treerinxlx864xn','irina@yandex.ru',  '2000-09-14', '2023-09-08', 'irinasav.jpg'),
       ('Ольга', 'Петрова', 'Olga', 'green', 'hjj76gvjdckdnck', 'olgapetrova@ya.ru', '1991-02-12', '2023-08-30', 'https://pgcookbook.ru/programming/olga.jpg');

DELETE
FROM subjects
WHERE subjects.id_subject > 0;
INSERT INTO subjects (name)
VALUES ('Математика'),
       ('Русский язык'),
       ('Литературное чтение'),
       ('Технология'),
       ('Английский язык'),
       ('Информатика'),
       ('Физкультура');



INSERT INTO lessons (user_id, subject_id, topic, date, time_start, time_end, theory_url, practice_url, homework_url,
                     progress,check_successfully)
VALUES ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Математика'),'Считаем до 5',
        '2023-09-11', '09:00:00', '09:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
         0, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Технология'),'Переходим дорогу',
        '2023-09-11', '10:00:00', '10:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
         0, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Английский язык'),'Осень',
        '2023-09-11', '12:00:00', '12:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        0, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Информатика'),'Новая тема',
        '2023-09-11', '13:00:00', '13:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        0, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Физкультура'),'Счет на палочках',
        '2023-09-11', '14:00:00', '14:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        0, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Математика'),'Новинки осеннего сезона',
        '2023-09-12', '09:00:00', '09:40:00','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        0, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Русский язык'),'Медузы',
        '2023-09-12', '10:00:00', '10:40:00',  'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        0, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Русский язык'),'Медузы',
        '2023-09-12', '12:00:00', '12:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        100, true),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Литературное чтение'),'Коллекции',
        '2023-09-12', '13:00:00', '13:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        10, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Физкультура'),'Устный счет',
        '2023-09-12', '15:00:00', '15:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        0, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Математика'),'Краски лета',
        '2023-09-13', '10:00:00', '10:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        10, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Литературное чтение'),'Весна',
        '2023-09-13', '13:00:00', '13:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        10, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Русский язык'),'Знаки препинанания',
        '2023-09-13', '14:00:00', '14:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        0, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Математика'),'Устный счет',
        '2023-09-13', '15:00:00', '15:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        0, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Русский язык'),'Дорожное движение',
        '2023-09-14', '09:00:00', '09:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        0, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Математика'),'Предлоги',
        '2023-09-14', '09:40:00', '09:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        10, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Литературное чтение'),'Грузовые машины',
        '2023-09-14', '10:00:00', '10:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        20,false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Технология'),'Медузы',
        '2023-09-14', '11:00:00', '11:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        35, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Английский язык'),'Лепка из пластилина',
        '2023-09-14', '12:00:00', '12:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        55, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Английский язык'),'Герои русских сказок',
        '2023-09-14', '16:00:00', '16:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        100, true),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Информатика'),'Счет на палочках',
        '2023-09-15', '09:00:00', '09:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        100,true),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Физкультура'),'Изучение Scratch',
        '2023-09-15', '12:00:00', '12:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        59, false),
       ((SELECT users.id_user FROM users WHERE users.login='irinasav'),
        (SELECT subjects.id_subject FROM subjects WHERE subjects.name='Физкультура'),'Изучение Scratch',
        '2023-09-17', '12:00:00', '12:40:00', 'https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm','https://pgcookbook.ru/programming/1.htm',
        59, false);